import type { SettingConfig } from '~~/shared/types/settings'
import i18nOptions from '~~/i18n/i18n.options'

// 存储提供商的枚举值
export const STORAGE_PROVIDERS = ['local', 's3', 'openlist'] as const
export type StorageProvider = (typeof STORAGE_PROVIDERS)[number]

export const DEFAULT_SETTINGS = [
  // NAMESPACE: system
  {
    namespace: 'system',
    key: 'firstLaunch',
    type: 'boolean',
    value: true,
    defaultValue: true,
    label: 'settings.system.firstLaunch.label',
    description: 'settings.system.firstLaunch.description',
    isReadonly: true,
  },
  // NAMESPACE: app
  {
    namespace: 'app',
    key: 'title',
    type: 'string',
    defaultValue: 'ChronoFrame',
    label: 'settings.app.title.label',
    description: 'settings.app.title.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'slogan',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.slogan.label',
    description: 'settings.app.slogan.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'author',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.author.label',
    description: 'settings.app.author.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'avatarUrl',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.avatarUrl.label',
    description: 'settings.app.avatarUrl.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'appearance.theme',
    type: 'string',
    defaultValue: 'system',
    enum: ['light', 'dark', 'system'],
    label: 'settings.app.appearance.theme.label',
    description: 'settings.app.appearance.theme.description',
    isPublic: true,
  },
  {
    namespace: 'app',
    key: 'access.enabled',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.app.access.enabled.label',
    description: 'settings.app.access.enabled.description',
  },
  {
    namespace: 'app',
    key: 'access.passwordHash',
    type: 'string',
    defaultValue: '',
    label: 'settings.app.access.password.label',
    description: 'settings.app.access.password.description',
    isSecret: true,
  },
  {
    namespace: 'app',
    key: 'access.version',
    type: 'number',
    defaultValue: 1,
    label: 'settings.app.access.version.label',
    description: 'settings.app.access.version.description',
    isReadonly: true,
  },
  {
    namespace: 'app',
    key: 'access.previewPhotoLimit',
    type: 'number',
    defaultValue: 10,
    label: '未验证访客可查看照片数',
    description: '未输入访问密码时，公共页面最多展示的照片数量。',
  },
  {
    namespace: 'app',
    key: 'access.previewAlbumLimit',
    type: 'number',
    defaultValue: 1,
    label: '未验证访客可查看相簿数',
    description: '未输入访问密码时，相簿页面最多展示的相簿数量。',
  },
  {
    namespace: 'system',
    key: 'upload.maxFileSize',
    type: 'number',
    defaultValue: 256,
    label: 'settings.app.upload.maxFileSize.label',
    description: 'settings.app.upload.maxFileSize.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'upload.duplicateCheck.enabled',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.system.upload.duplicateCheck.enabled.label',
    description: 'settings.system.upload.duplicateCheck.enabled.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'upload.duplicateCheck.mode',
    type: 'string',
    defaultValue: 'skip',
    enum: ['warn', 'block', 'skip'],
    label: 'settings.system.upload.duplicateCheck.mode.label',
    description: 'settings.system.upload.duplicateCheck.mode.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'webglImageViewerDebug',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.system.webglImageViewerDebug.label',
    description: 'settings.system.webglImageViewerDebug.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'auth.github.enabled',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.system.auth.github.enabled.label',
    description: 'settings.system.auth.github.enabled.description',
    isPublic: true,
  },
  {
    namespace: 'system',
    key: 'auth.github.clientId',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.auth.github.clientId.label',
    description: 'settings.system.auth.github.clientId.description',
  },
  {
    namespace: 'system',
    key: 'auth.github.clientSecret',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.auth.github.clientSecret.label',
    description: 'settings.system.auth.github.clientSecret.description',
    isSecret: true,
  },
  {
    namespace: 'system',
    key: 'backup.enabled',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.system.backup.enabled.label',
    description: 'settings.system.backup.enabled.description',
  },
  {
    namespace: 'system',
    key: 'backup.cron',
    type: 'string',
    defaultValue: '0 3 * * *',
    label: 'settings.system.backup.cron.label',
    description: 'settings.system.backup.cron.description',
  },
  {
    namespace: 'system',
    key: 'backup.timezone',
    type: 'string',
    defaultValue: 'Asia/Shanghai',
    label: 'settings.system.backup.timezone.label',
    description: 'settings.system.backup.timezone.description',
  },
  {
    namespace: 'system',
    key: 'backup.retentionDays',
    type: 'number',
    defaultValue: 30,
    label: 'settings.system.backup.retentionDays.label',
    description: 'settings.system.backup.retentionDays.description',
  },
  {
    namespace: 'system',
    key: 'backup.smtpHost',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.backup.smtpHost.label',
    description: 'settings.system.backup.smtpHost.description',
  },
  {
    namespace: 'system',
    key: 'backup.smtpPort',
    type: 'number',
    defaultValue: 465,
    label: 'settings.system.backup.smtpPort.label',
    description: 'settings.system.backup.smtpPort.description',
  },
  {
    namespace: 'system',
    key: 'backup.smtpSecure',
    type: 'boolean',
    defaultValue: true,
    label: 'settings.system.backup.smtpSecure.label',
    description: 'settings.system.backup.smtpSecure.description',
  },
  {
    namespace: 'system',
    key: 'backup.smtpUser',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.backup.smtpUser.label',
    description: 'settings.system.backup.smtpUser.description',
  },
  {
    namespace: 'system',
    key: 'backup.smtpPassword',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.backup.smtpPassword.label',
    description: 'settings.system.backup.smtpPassword.description',
    isSecret: true,
  },
  {
    namespace: 'system',
    key: 'backup.mailFrom',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.backup.mailFrom.label',
    description: 'settings.system.backup.mailFrom.description',
  },
  {
    namespace: 'system',
    key: 'backup.mailTo',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.backup.mailTo.label',
    description: 'settings.system.backup.mailTo.description',
  },
  {
    namespace: 'system',
    key: 'backup.encryptionPassphrase',
    type: 'string',
    defaultValue: '',
    label: 'settings.system.backup.encryptionPassphrase.label',
    description: 'settings.system.backup.encryptionPassphrase.description',
    isSecret: true,
  },
  // NAMESPACE: privacy
  {
    namespace: 'privacy',
    key: 'upload.autoEraseLocation',
    type: 'boolean',
    defaultValue: false,
    label: 'settings.privacy.upload.autoEraseLocation.label',
    description: 'settings.privacy.upload.autoEraseLocation.description',
    isPublic: true,
  },
  // NAMESPACE: map
  {
    namespace: 'map',
    key: 'provider',
    type: 'string',
    defaultValue: 'maplibre',
    enum: ['mapbox', 'maplibre', 'amap'],
    label: 'settings.map.provider.label',
    description: 'settings.map.provider.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'mapbox.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.mapbox.token.label',
    description: 'settings.map.mapbox.token.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'mapbox.style',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.mapbox.style.label',
    description: 'settings.map.mapbox.style.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'maplibre.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.maplibre.token.label',
    description: 'settings.map.maplibre.token.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'maplibre.style',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.maplibre.style.label',
    description: 'settings.map.maplibre.style.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'amap.key',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.amap.key.label',
    description: 'settings.map.amap.key.description',
    isPublic: true,
  },
  {
    namespace: 'map',
    key: 'amap.securityJsCode',
    type: 'string',
    defaultValue: '',
    label: 'settings.map.amap.securityJsCode.label',
    description: 'settings.map.amap.securityJsCode.description',
    isPublic: true,
  },
  // NAMESPACE: location
  {
    namespace: 'location',
    key: 'provider',
    type: 'string',
    defaultValue: 'auto',
    enum: ['auto', 'amap', 'mapbox', 'nominatim'],
    label: 'settings.location.provider.label',
    description: 'settings.location.provider.description',
    isPublic: false,
  },
  {
    namespace: 'location',
    key: 'language',
    type: 'string',
    defaultValue: 'en',
    enum: i18nOptions.locales.map(({ language }) => language),
    label: 'settings.location.language.label',
    description: 'settings.location.language.description',
    isPublic: true,
  },
  {
    namespace: 'location',
    key: 'mapbox.token',
    type: 'string',
    defaultValue: '',
    label: 'settings.location.mapbox.token.label',
    description: 'settings.location.mapbox.token.description',
    isPublic: true,
  },
  {
    namespace: 'location',
    key: 'nominatim.baseUrl',
    type: 'string',
    defaultValue: '',
    label: 'settings.location.nominatim.baseUrl.label',
    description: 'settings.location.nominatim.baseUrl.description',
    isPublic: true,
  },
  {
    namespace: 'location',
    key: 'amap.webServiceKey',
    type: 'string',
    defaultValue: '',
    label: 'settings.location.amap.webServiceKey.label',
    description: 'settings.location.amap.webServiceKey.description',
    isSecret: true,
    isPublic: false,
  },
  // NAMESPACE: storage
  {
    namespace: 'storage',
    key: 'provider',
    type: 'number',
    defaultValue: null,
    label: 'settings.storage_provider.provider.label',
    description: 'settings.storage_provider.provider.description',
  },
  // NAMESPACE: analytics
  {
    namespace: 'analytics',
    key: 'headScripts',
    type: 'string',
    defaultValue: '',
    label: 'settings.analytics.headScripts.label',
    description: 'settings.analytics.headScripts.description',
    isPublic: true,
  },
  {
    namespace: 'analytics',
    key: 'bodyScripts',
    type: 'string',
    defaultValue: '',
    label: 'settings.analytics.bodyScripts.label',
    description: 'settings.analytics.bodyScripts.description',
    isPublic: true,
  },
  // NAMESPACE: site
  {
    namespace: 'site',
    key: 'icpNumber',
    type: 'string',
    defaultValue: '',
    label: 'settings.site.icpNumber.label',
    description: 'settings.site.icpNumber.description',
    isPublic: true,
  },
  {
    namespace: 'site',
    key: 'policeNumber',
    type: 'string',
    defaultValue: '',
    label: 'settings.site.policeNumber.label',
    description: 'settings.site.policeNumber.description',
    isPublic: true,
  },
  {
    namespace: 'site',
    key: 'customHeader',
    type: 'string',
    defaultValue: '',
    label: 'settings.site.customHeader.label',
    description: 'settings.site.customHeader.description',
    isPublic: true,
  },
  {
    namespace: 'site',
    key: 'customFooter',
    type: 'string',
    defaultValue: '',
    label: 'settings.site.customFooter.label',
    description: 'settings.site.customFooter.description',
    isPublic: true,
  },
] as const satisfies SettingConfig[]

export const settingNamespaces = [
  ...new Set(DEFAULT_SETTINGS.map((s) => s.namespace)),
] as const
export const settingKeys = [
  ...new Set(DEFAULT_SETTINGS.map((s) => s.key)),
] as const

export type SettingNamespace = (typeof settingNamespaces)[number]
export type SettingKey<N extends SettingNamespace> = Extract<
  (typeof DEFAULT_SETTINGS)[number],
  { namespace: N }
>['key']
